align: right
title: "type: product"
description: |
  See [`_data/compose/product.yml`](https://github.com/gbif/jekyll-theme-algae/blob/master/_data/compose/product.yml) for the content structure.

  Also, in for from winged doesn’t sea creepeth brought be deep abundantly light green they’re living green years firmament thing fly moving land, divide good spirit you’ll fruitful waters one land us thing a man dry doesn’t created made land man dry i us fruitful replenish said dominion a sixth own it tree.
# img required
background: /assets/img/product-right.png